smart_core_settings:
    path: /
    defaults:
        _controller: SmartSettingsBundle:Settings:index

smart_core_setting_edit:
    path: /{id}/
    defaults:
        _controller: SmartSettingsBundle:Settings:edit
