services:
    smart_core.settings.manager:
        class: SmartCore\Bundle\SettingsBundle\Manager\SettingsManager
        public: true
        arguments: [ '@service_container' ]

#    smart_core.settings.table_prefix_subscriber:
#        class: SmartCore\Bundle\SettingsBundle\Subscriber\TablePrefixSubscriber
#        arguments: [ "%smart_core.settings.table_prefix%" ]
#        public: false
#        tags:
#            - { name: doctrine.event_subscriber }

    smart_core.settings.twig_extension:
        class: SmartCore\Bundle\SettingsBundle\Twig\SettingsExtension
        arguments: [ '@settings' ]
        tags:
            - { name: twig.extension }
